### ISSUE TITLE
NEXT_DATA typization

### ISSUE THREAD

**Issue by TFK70** [atls/nextjs#222]
### Описание бага

Встречается в пакетах, где есть обращение к `window.__NEXT_DATA__`

По дефолту у window нету свойства `__NEXT_DATA__`, так что нам нужно его туда добавить

Проблема встречалась и ранее, так что вот полная хронология:

**Начальное состояние**

Изначально эта проблема решалась так:

```javascript
declare global {
  interface Window {
    __NEXT_DATA__: any
  }
}
```

Все было нормально до того момента, пока мы не обновили typescript до 4 мажорной. Ошибка выглядела так:

<details>

```javascript
Type error: Subsequent property declarations must have the same type.  Property '__NEXT_DATA__' must be of type 'NEXT_DATA', but here has type 'any'.

  3 | declare global {
  4 |     interface Window {
> 5 |         __NEXT_DATA__: any;
    |         ^
  6 |     }
  7 | }
  8 | declare type Props = {
```

</details>

**Воспроизведение:**

Для воспроизведение можно использовать `@monstrs/next-app-with-intl@0.3.13`, там такая же проблема (с ходу не нашел `@atls` либ более ранних версий в регистре, где бы это воспроизводилось)

Нужно установить ее в проект с `typescript@4.3.5` и запустить typecheck (но само приложение будет работать)

**"Фикс"**

Для фикса этой проблемы, очевидно, нужно было получить тип NEXT_DATA, о котором он писал в логах, и он должен был находиться в где-то next, но проблема в том, что просто так его взять и заимпортить нельзя - его нет в индексе.

Проблема решается если добираться до файла с этим типом вручную через релятивные пути:

```javascript
require('next/dist/next-server/lib/utils')
```

Там есть NEXT_DATA и он нам подходит, но проблема в том, что в разных версиях некста путь до этого файла тоже разный, так что была использована следующая заплатка (на данный момент актуальная):

```javascript
const NEXT_DATA_VAL = (require('next/dist/shared/lib/utils') || require('next/dist/next-server/lib/utils')).NEXT_DATA

type NEXT_DATA = typeof NEXT_DATA_VAL

declare global {
  interface Window {
    __NEXT_DATA__: NEXT_DATA
  }
}
```

Ранее она работала, но [здесь](https://github.com/torin-asakura/drum-in/tree/feature/apply-styles) она выстрелила следующим образом:

<details>

![image](https://user-images.githubusercontent.com/62806448/146043451-259236ed-c053-46c3-b89c-84cfb90e2ccb.png)

</details>

Только в этом случае уже не билдится проект: он не может достучаться до файла, откуда мы берем NEXT_DATA

### Воспроизведение

Получается шаги для воспроизведения бага следующие:

1. Устанавливаем на проекте `@atls/next-app-with-intl@0.2.75` и `next@11` или `next@10.0.5` (проверялось на обоих)
2. Билдим проект
3. Видим ошибку

Но проблема в том, что есть проекты где с аналогичным окружением все в порядке, так что шаги могут сработать, а могут и не сработать, на данный момент не могу быть уверен в чем именно причина

### Ожидаемое поведение

Тайпчеки проходят, проект билдится

### Данные окружения

- macOS@monterey и Windows 10

**Comment by TorinAsakura** [comment]
Deprecated by https://github.com/atls/nextjs/releases/tag/legacy
